### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by chaaals** [marcusandrev/springcrate#19]
## Tasks
- [x] Familiarize w/ Bloc Architecture
- [x] Apply refetching algorithm
- [x] Apply refetch on search in transactions
- [x] Apply refetch on add in transactions
- [x] Apply refetch on search in services
- [x] Apply refetch on add in services
- [x] Apply refetch on search in employee
