### ISSUE TITLE
Display Employee Info From the Database

### ISSUE THREAD

**Issue by b0kja85** [marcusandrev/springcrate#9]
_The data for Employees is hardcoded as it only access the dummy data._ 

![image](https://github.com/marcusandrev/springcrate/assets/88694450/f03c1b38-a4bb-42b8-a641-c3e9cd66dbfc)
![image](https://github.com/marcusandrev/springcrate/assets/88694450/005e1a66-3530-4c31-8b68-8d8d01f605e3)

**Solution:**
1.  Connect the Firestore Database 
2. Implement BloC Architecture 

**To-do:**
1.  [ ] Get the Data from the database
2.  [ ] Display the Data in the Transactions Card
3.  [ ] Display the Data in the Employee Details Screen
